## Compress

Observability systems may receive a very large amount of data every day. In addition to data governance, what other methods can help reduce disk usage? One recommended approach is to use the ZSTD compression algorithm to compress data efficiently and reduce storage consumption.

The logs have already been imported into the `otel_logs` table. That table uses the default compression algorithm, LZ4F. To compare it with the default `otel_logs` table, create a new table named `otel_logs_zstd`:

### Initialize the Lab

Run this cell once before using `lab.shell(...)` or `lab.sql(...)`.

In [1]:
from pathlib import Path
import sys

COURSE_ROOT = next(
    path for path in (Path.cwd(), *Path.cwd().parents)
    if (path / "doris_course").is_dir()
)
if str(COURSE_ROOT) not in sys.path:
    sys.path.insert(0, str(COURSE_ROOT))

from doris_course import DorisLab

lab = DorisLab(lab_dir=COURSE_ROOT)

In [2]:
lab.execute(r"""
CREATE TABLE `otel_logs_zstd` (
  `timestamp` datetime(6) NULL,
  `service_name` varchar(200) NULL,
  `service_instance_id` varchar(200) NULL,
  `trace_id` varchar(200) NULL,
  `span_id` text NULL,
  `severity_number` int NULL,
  `severity_text` text NULL,
  `body` text NULL,
  `resource_attributes` variant NULL,
  `log_attributes` variant NULL,
  `scope_name` text NULL,
  `scope_version` text NULL,
  INDEX idx_service_name (`service_name`) USING INVERTED,
  INDEX idx_timestamp (`timestamp`) USING INVERTED,
  INDEX idx_service_instance_id (`service_instance_id`) USING INVERTED,
  INDEX idx_trace_id (`trace_id`) USING INVERTED,
  INDEX idx_span_id (`span_id`) USING INVERTED,
  INDEX idx_severity_number (`severity_number`) USING INVERTED,
  INDEX idx_body (`body`) USING INVERTED PROPERTIES("lower_case" = "true", "parser" = "unicode", "support_phrase" = "true"),
  INDEX idx_severity_text (`severity_text`) USING INVERTED,
  INDEX idx_resource_attributes (`resource_attributes`) USING INVERTED,
  INDEX idx_log_attributes (`log_attributes`) USING INVERTED,
  INDEX idx_scope_name (`scope_name`) USING INVERTED,
  INDEX idx_scope_version (`scope_version`) USING INVERTED
) ENGINE=OLAP
DUPLICATE KEY(`timestamp`, `service_name`)
PARTITION BY RANGE(`timestamp`)
(PARTITION p20260908 VALUES [('2026-09-08 00:00:00'), ('2026-09-09 00:00:00')),
PARTITION p20260909 VALUES [('2026-09-09 00:00:00'), ('2026-09-10 00:00:00')),
PARTITION p20260910 VALUES [('2026-09-10 00:00:00'), ('2026-09-11 00:00:00')),
PARTITION p20260911 VALUES [('2026-09-11 00:00:00'), ('2026-09-12 00:00:00')),
PARTITION p20260912 VALUES [('2026-09-12 00:00:00'), ('2026-09-13 00:00:00')),
PARTITION p20260913 VALUES [('2026-09-13 00:00:00'), ('2026-09-14 00:00:00')),
PARTITION p20260914 VALUES [('2026-09-14 00:00:00'), ('2026-09-15 00:00:00')),
PARTITION p20260915 VALUES [('2026-09-15 00:00:00'), ('2026-09-16 00:00:00')),
PARTITION p20260916 VALUES [('2026-09-16 00:00:00'), ('2026-09-17 00:00:00')),
PARTITION p20260917 VALUES [('2026-09-17 00:00:00'), ('2026-09-18 00:00:00')),
PARTITION p20260918 VALUES [('2026-09-18 00:00:00'), ('2026-09-19 00:00:00')),
PARTITION p20260919 VALUES [('2026-09-19 00:00:00'), ('2026-09-20 00:00:00')))
DISTRIBUTED BY RANDOM BUCKETS AUTO
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Etc/UTC",
"dynamic_partition.start" = "-10",
"dynamic_partition.end" = "1",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_allocation" = "tag.location.default: 1",
"dynamic_partition.buckets" = "10",
"dynamic_partition.create_history_partition" = "true",
"dynamic_partition.history_partition_num" = "10",
"dynamic_partition.hot_partition_num" = "0",
"dynamic_partition.reserved_history_periods" = "NULL",
"dynamic_partition.storage_policy" = "",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V2",
"light_schema_change" = "true",
"compaction_policy" = "time_series",
"time_series_compaction_goal_size_mbytes" = "1024",
"time_series_compaction_file_count_threshold" = "2000",
"time_series_compaction_time_threshold_seconds" = "3600",
"time_series_compaction_empty_rowsets_threshold" = "5",
"time_series_compaction_level_threshold" = "1",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"compression" = "zstd"
);
""", title='ZSTD-compressed log table')

0

Note the final property, `"compression" = "zstd"`. It specifies that the ZSTD compression algorithm is used.

Next, insert the data from `otel_logs` into `otel_logs_zstd`:

In [3]:
lab.execute("INSERT INTO otel_logs_zstd SELECT * FROM otel_logs")

97055

Because the data files are not large, this example is intended only to show the difference. In scenarios with larger data volumes, ZSTD can provide better compression results:

<img src="images/compress.png" alt="Comparison of LZ4F and ZSTD compression in Doris" style="max-width:100%;height:auto;">

## Materialized Views

In metrics scenarios, if you need to analyze the maximum value of certain `metric_name` values over a historical period, you can query the `otel_metrics_gauge` table directly. However, this table stores the original metrics data, and direct aggregation can be inefficient. Doris materialized views can be used to accelerate these queries.

The `otel_metrics_gauge` table has already been created. You only need to create a materialized view on this table to accelerate the required query:

In [4]:
lab.execute(r"""
CREATE MATERIALIZED VIEW mv_for_metrics AS
SELECT metric_name AS mn, MAX(value) AS max_value
FROM otel_metrics_gauge
GROUP BY metric_name;
""", title='Materialized view for metric maxima')

0

After the materialized view is created, you can query the original table without needing to remember that the materialized view exists:

In [5]:
lab.sql(r"""
SELECT metric_name, MAX(value) FROM otel_metrics_gauge GROUP BY metric_name LIMIT 5;
""", title='Metric maximum query')

                               metric_name    MAX(value)
0    scrape_samples_post_metric_relabeling  1.455000e+03
1                                       up  1.000000e+00
2      doris_be_thread_pool_max_queue_size  2.147484e+09
3                   doris_be_memory_pswpin  9.012000e+04
4                  doris_be_memory_pgpgout  1.340271e+07
..                                     ...           ...
178   doris_fe_tablet_max_compaction_score  1.500000e+01
179                      doris_fe_plan_num  1.000000e+00
180             doris_fe_report_queue_size  0.000000e+00
181    doris_fe_statistics_empty_table_num  5.000000e+00
182                              node_info  1.000000e+00

[183 rows x 2 columns]

This statement will hit the materialized view. Because the materialized view already contains aggregated data, the query will be accelerated. You can use `EXPLAIN` to confirm this:

<img src="images/explain.png" alt="EXPLAIN output showing that the materialized view is used" style="max-width:100%;height:auto;">

## Inverted Indexes

You may also have noticed that many of the preceding table definitions contain statements such as the following. These statements create inverted indexes:

The original log table contains the following inverted indexes:

```sql
...
  INDEX idx_service_name (`service_name`) USING INVERTED,
  INDEX idx_timestamp (`timestamp`) USING INVERTED,
  INDEX idx_service_instance_id (`service_instance_id`) USING INVERTED,
  INDEX idx_trace_id (`trace_id`) USING INVERTED,
  ...
```

How can you determine whether these indexes are being used and whether they reduce the amount of data that must be scanned?

Consider a simple scenario where you need to retrieve detailed logs whose `service_name` equals a specific value. The following statement can be generated quickly. The first two session variables enable profiling and set the profile level:

In [6]:
lab.execute("SET enable_profile = true")
lab.sql(r"""
SELECT * FROM otel_logs WHERE service_name = 'load-generator' LIMIT 10
""", title="Query with profile collection enabled")

Empty DataFrame
Columns: [timestamp, service_name, service_instance_id, trace_id, span_id, severity_number, severity_text, body, resource_attributes, log_attributes, scope_name, scope_version]
Index: []

Use the following statement to find the profile ID for the preceding query:

In [7]:
lab.sql(r"""
SHOW QUERY PROFILE
""", title='Recent query profiles')

,Profile ID,Task Type,Start Time,End Time,Total,Task State,User,Default Catalog,Default Db,Sql Statement
0,88e5c13d303b4385-8b6814758777d498,QUERY,2026-09-24 10:32:24,2026-09-24 10:32:25,997ms,OK,root,internal,otel,SELECT * FROM otel_logs WHERE service_name = '...

On the FE that executed the query, run the following command:

In [9]:
PROFILE_ID = "88e5c13d303b4385-8b6814758777d498	"
assert not PROFILE_ID.startswith("<"), "Replace PROFILE_ID with the ID shown by SHOW QUERY PROFILE."

lab.shell(f"""set -euo pipefail
curl -uroot: "http://127.0.0.1:8030/api/profile/text?query_id=88e5c13d303b4385-8b6814758777d498"
""", title="Fetch the Doris query profile")

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 25 16158   25  4136    0     0  17719      0 --:--:-- --:--:-- --:--:-- 17675
100 16158  100 16158    0     0  69171      0 --:--:-- --:--:-- --:--:-- 69051
Summary:
   - Profile ID: 88e5c13d303b4385-8b6814758777d498
   - Task Type: QUERY
   - Start Time: 2026-09-24 10:32:24
   - End Time: 2026-09-24 10:32:25
   - Total: 997ms
   - Task State: OK
   - User: root
   - Default Catalog: internal
   - Default Db: otel
   - Sql Statement: SELECT * FROM otel_logs WHERE service_name = 'load-generator' LIMIT 10
   - Distributed Plan: N/A
Execution Summary:
   - Workload Group: normal
   - Parse SQL Time: 3ms
   - Plan Time: 136ms
     - Garbage Collect During Plan Time: 0ms
     - Nereids Lock Table Time: 84ms
     - Nereids Analysis Time: 2ms
     - Nereids Rewrite Time: 8ms
       - Nereids Fold Const By BE Time: 0ms
     - Nereids Collect Table Partition Time: 0ms
   - Nereids Pre Rewrite By Mv Time: N/A
     - Nereids Optimize Time: N/A
     - Nereids Translate Time: 11ms
       - Init Scan Node Time: N/A
       - Finalize Scan Node Time: N/A
         - Get Splits Time: N/A
         - Get Partitions Time: N/A
         - Get Partition Files Time: N/A
         - Sink Set Partition Values Time: N/A
       - Create Scan Range Time: N/A
         - Iceberg Scan Metrics: N/A
         - Paimon Scan Metrics: N/A
     - Nereids Distribute Time: 14ms
   - Get Meta Version Time: N/A
     - Get Partition Version Time: N/A
     - Get Partition Version Count (hasData): N/A
     - Get Partition Version Count: N/A
     - Get Table Version Time: N/A
     - Get Table Version Count: N/A
   - Schedule Time: 88ms
     - Fragment Assign Time: 3ms
     - Fragment Serialize Time: 41ms
     - Fragment RPC Phase1 Time: 38ms
     - Fragment RPC Phase2 Time: 6ms
     - Fragment Compressed Size: 4.19 KB
     - Fragment RPC Count: 2
   - Schedule Time Of BE: {"phase1":{"127.0.0.1: 8060":{"RPC Work Time":"27ms","RPC Latency From FE To BE":"5ms","RPC Work Queue Time":"0ms","RPC Latency From BE To FE":"6ms"}},"phase2":{"127.0.0.1: 8060":{"RPC Work Time":"1ms","RPC Latency From FE To BE":"2ms","RPC Work Queue Time":"0ms","RPC Latency From BE To FE":"3ms"}}}
   - Wait and Fetch Result Time: 769ms
   - Fetch Result Time: 714ms
   - Write Result Time: 0ms
   - Doris Version: doris-4.0.3-rc03-e9096296b8b
   - Is Nereids: Yes
   - Is Cached: No
   - Total Instances Num: 2
   - Instances Num Per BE: 127.0.0.1:8060:2
   - Parallel Fragment Exec Instance Num: 4
   - Trace ID:
   - Transaction Commit Time: N/A
   - System Message: N/A
   - Executed By Frontend: N/A
   - Splits Assignment Weight: N/A

ChangedSessionVariables:
[
  {
    "VarName": "enable_profile",
    "CurrentValue": "true",
    "DefaultValue": "false"
  }
]
MergedProfile:
     Fragments:
       Fragment 0:
         Pipeline 0(instance_num=1):
            - WaitWorkerTime: avg 75.917us, max 75.917us, min 75.917us
           RESULT_SINK_OPERATOR(id=2147483647):
             CommonCounters:
                - ExecTime: avg 2.505ms, max 2.505ms, min 2.505ms
                - InputRows: sum 0, avg 0, max 0, min 0
                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - WaitForDependency[RESULT_SINK_OPERATOR_DEPENDENCY]Time: avg 0ns, max 0ns, min 0ns
             CustomCounters:
                - WaitForDependencyTime: avg 0ns, max 0ns, min 0ns
           EXCHANGE_OPERATOR(id=1):
              - PlanInfo
                 - offset: 0
                 - limit: 10
             CommonCounters:
                - BlocksProduced: sum 0, avg 0, max 0, min 0
                - ExecTime: avg 1.32ms, max 1.32ms, min 1.32ms
                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - RowsProduced: sum 0, avg 0, max 0, min 0
             CustomCounters:
                - WaitForDependencyTime: avg 0ns, max 0ns, min 0ns
                  - WaitForData0: avg 767.158ms, max 767.158ms, min 767.158ms
       Fragment 1:
         Pipeline 0(instance_num=1):
            - WaitWorkerTime: avg 627.415us, max 627.415us, min 627.415us
           DATA_STREAM_SINK_OPERATOR(dest_id=1):
             CommonCounters:
                - ExecTime: avg 2.872ms, max 2.872ms, min 2.872ms
                - InputRows: sum 0, avg 0, max 0, min 0
                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - WaitForDependencyTime: avg 0ns, max 0ns, min 0ns
                  - WaitForRpcBufferQueue: avg 0ns, max 0ns, min 0ns
             CustomCounters:
                - BlocksProduced: sum 1, avg 1, max 1, min 1
                - OverallThroughput: sum 0.0 /sec, avg 0.0 /sec, max 0.0 /sec, min 0.0 /sec
           OLAP_SCAN_OPERATOR(nereids_id=123. table_name=otel_logs(otel_logs))(id=0):
              - PlanInfo
                 - TABLE: otel.otel_logs(otel_logs), PREAGGREGATION: ON
                 - PREDICATES: (service_name = 'load-generator')
                 - partitions=1/5 (p20260924)
                 - tablets=10/10, tabletList=1790240551126,1790240551128,1790240551130 ...
                 - cardinality=10, avgRowSize=5585.4287, numNodes=1
                 - pushAggOp=NONE
                 - limit: 10
             CommonCounters:
                - BlocksProduced: sum 0, avg 0, max 0, min 0
                - ExecTime: avg 248.613ms, max 248.613ms, min 248.613ms
                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - RowsProduced: sum 0, avg 0, max 0, min 0
                - WaitForDependency[OLAP_SCAN_OPERATOR_DEPENDENCY]Time: avg 157.662ms, max 157.662ms, min 157.662ms
             CustomCounters:
                - RuntimeFilterInfo: sum , avg , max , min
                - ScanBytes: sum 0.00 , avg 0.00 , max 0.00 , min 0.00
                - ScanRows: sum 0, avg 0, max 0, min 0

DetailProfile(88e5c13d303b4385-8b6814758777d498):
  Fragments:
    Fragment 0:
      FragmentLevelProfile:(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):
      Pipeline 0(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):
        PipelineTask(index=0):
           - TaskState: FINALIZED
           - BlockedByDependency:
           - WakeUpEarly: 0
           - WaitWorkerTime: 75.917us
          RESULT_SINK_OPERATOR(id=2147483647):
            CommonCounters:
               - ExecTime: 2.505ms
               - InputRows: 0
               - MemoryUsage: 0.00
               - MemoryUsagePeak: 0.00
               - WaitForDependency[RESULT_SINK_OPERATOR_DEPENDENCY]Time: 0ns
            CustomCounters:
               - WaitForDependencyTime: 0ns
          EXCHANGE_OPERATOR(id=1):
            CommonCounters:
               - BlocksProduced: 0
               - ExecTime: 1.32ms
               - MemoryUsage: 0.00
               - MemoryUsagePeak: 0.00
               - RowsProduced: 0
            CustomCounters:
               - InstanceID: 88e5c13d303b4385-8b6814758777d4a6
               - WaitForDependencyTime: 0ns
                 - WaitForData0: 767.158ms
    Fragment 1:
      FragmentLevelProfile:(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):
      Pipeline 0(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):
        PipelineTask(index=0):
           - TaskState: FINALIZED
           - BlockedByDependency:
           - WakeUpEarly: 0
           - WaitWorkerTime: 627.415us
          DATA_STREAM_SINK_OPERATOR(dest_id=1):
            CommonCounters:
               - ExecTime: 2.872ms
               - InputRows: 0
               - MemoryUsage: 0.00
               - MemoryUsagePeak: 0.00
               - WaitForDependencyTime: 0ns
                 - WaitForRpcBufferQueue: 0ns
            CustomCounters:
               - BlocksProduced: 1
               - OverallThroughput: 0.0 /sec
          OLAP_SCAN_OPERATOR(nereids_id=123. table_name=otel_logs(otel_logs))(id=0):
            CommonCounters:
               - BlocksProduced: 0
               - ExecTime: 248.613ms
               - MemoryUsage: 0.00
               - MemoryUsagePeak: 0.00
               - RowsProduced: 0
               - WaitForDependency[OLAP_SCAN_OPERATOR_DEPENDENCY]Time: 157.662ms
            CustomCounters:
               - TopNFilterSourceNodeIds:
               - PushDownPredicates: Slot ID: 1: [{ComparisonPredicateBase(Column ID: 1, Data Type: VARCHAR, PredicateType: eq, opposite: false, Runtime Filter ID: -1)}, ]
               - RemainedDownPredicates:
               - KeyRanges: ScanKeys:ScanKey=[null(0000-01-01 00:00:00) : 9999-12-31 23:59:59.999999]
               - TabletIds: [1790240551126, 1790240551128, 1790240551130, 1790240551132, 1790240551134, 1790240551136, 1790240551138, 1790240551140, 1790240551142, 1790240551144]
               - RuntimeFilterInfo:
               - ScanBytes: 0.00
               - ScanRows: 0
              Scanner:
                 - ReadColumns: [timestamp, service_name, service_instance_id, trace_id, span_id, severity_number, severity_text, body, resource_attributes, log_attributes, scope_name
, scope_version]
                 - PerScannerRunningTime: [1.541us, 1.166us, 2.916us, 1.166us, 2.708us, 5.209us, 4.333us, 2.334us, 6.125us, 5.292us, ]
                 - PerScannerRowsRead: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ]
                 - PerScannerWaitTime: [751.792us, 381.916us, 365.834us, 928.250us, 161.125us, 143.583us, 2.122ms, 235.916us, 392.208us, 175.875us, ]
                 - PerScannerProjectionTime: [0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, ]
                 - EOS: True
                SegmentIterator:
                   - FileCache: 0ns
                     - BytesScannedFromCache: 0.00
                     - BytesScannedFromPeer: 0.00
                     - BytesScannedFromRemote: 0.00
                     - BytesWriteIntoCache: 0.00
                     - CacheGetOrSetTimer: 0ns
                     - GetTimer: 0ns
                     - InvertedIndexBytesScannedFromCache: 0.00
                     - InvertedIndexBytesScannedFromPeer: 0.00
                     - InvertedIndexBytesScannedFromRemote: 0.00
                     - InvertedIndexIOTimer: 0ns
                     - InvertedIndexLocalIOUseTimer: 0ns
                     - InvertedIndexNumLocalIOTotal: 0
                     - InvertedIndexNumPeerIOTotal: 0
                     - InvertedIndexNumRemoteIOTotal: 0
                     - InvertedIndexPeerIOUseTimer: 0ns
                     - InvertedIndexRemoteIOUseTimer: 0ns
                     - LocalIOUseTimer: 0ns
                     - LockWaitTimer: 0ns
                     - NumLocalIOTotal: 0
                     - NumPeerIOTotal: 0
                     - NumRemoteIOTotal: 0
                     - NumSkipCacheIOTotal: 0
                     - PeerIOUseTimer: 0ns
                     - ReadCacheFileDirectlyTimer: 0ns
                     - RemoteIOUseTimer: 0ns
                     - SetTimer: 0ns
                     - WaitOtherDownloaderTimer: 0ns
                     - WriteCacheIOUseTimer: 0ns
                IndexFilter:
  LoadChannels:

Appendix:

PhysicalPlan:
PhysicalResultSink[143] ( outputExprs=[timestamp#0, service_name#1, service_instance_id#2, trace_id#3, span_id#4, severity_number#5, severity_text#6, body#7, resource_attributes#8, log_attributes#9, scope_name#10, scope_version#11] )
     +--PhysicalLimit[139]@3 ( limit=10, offset=0, phase=GLOBAL, stats=10 )
        +--PhysicalDistribute[135]@2 ( stats=10, distributionSpec=DistributionSpecGather )
           +--PhysicalLimit[131]@2 ( limit=10, offset=0, phase=LOCAL, stats=10 )
              +--PhysicalFilter[127]@1 ( stats=3,451.5, predicates=(service_name#1 = 'load-generator') )
                 +--PhysicalOlapScan[otel_logs partitions(1/5)]@0 ( stats=96,267(6903) actualRows=0, operativeSlots=[service_name#1], virtualColumns=[] )
     PhysicalOlapScan[otel_logs partitions(1/5)]@0 ( stats=96,267(6903) actualRows=0, operativeSlots=[service_name#1], virtualColumns=[] )
       timestamp#0 -> ndv=52056.0000, min=20260924164055.000000(2026-09-24 16:40:55.847000), max=20260924182655.000000(2026-09-24 18:26:55.379000), count=96267.0000, numNulls=0.0000, avgSizeByte=8.000000, hotValues=(null)
       service_name#1 -> ndv=1.0000, min=0.000000(), max=0.000000(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=('':1.0)
       service_instance_id#2 -> ndv=1.0000, min=0.000000(), max=0.000000(), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=('':1.0)
       trace_id#3 -> ndv=1.0000, min=0.000000(), max=0.000000(), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=('':1.0)
       span_id#4 -> ndv=1.0000, min=0.000000(), max=0.000000(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=('':1.0)
       severity_number#5 -> ndv=3.0000, min=9.000000(9), max=17.000000(17), count=96267.0000, numNulls=0.0000, avgSizeByte=4.000000, hotValues=(9:1.0)
       severity_text#6 -> ndv=3.0000, min=19512286864605184.000000(ERROR), max=24560144725573632.000000(WARN), count=96267.0000, numNulls=0.0000, avgSizeByte=4.000352, hotValues=('INFO':1.0)
       body#7 -> ndv=82518.0000, min=23210065350192484.000000(RuntimeLogger 2026-09-24 08:40:55,847 INFO (main|1) [LogUtils.stdout():50] StdoutLogger 2026-09-24 08:40:55,844 Build version: doris-4.0.3-rc03), max=23210065350192484.000000(RuntimeLogger 2026-09-24 10:26:55,379 INFO (tablet scheduler|36) [TabletScheduler.runAfterCatalogReady():366] finished to tablet scheduler. cost: 1 ms), count=96267.0000, numNulls=0.0000, avgSizeByte=291.467595, hotValues=(null)
       resource_attributes#8 -> unknown(96267.0)
       log_attributes#9 -> unknown(96267.0)
       scope_name#10 -> ndv=1.0000, min=0.000000(), max=0.000000(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=('':1.0)
       scope_version#11 -> ndv=1.0000, min=0.000000(), max=0.000000(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=('':1.0)

CompletedProcess(args=['/bin/bash', '-lc', 'set -euo pipefail\ncurl -uroot: "http://127.0.0.1:8030/api/profile/text?query_id=88e5c13d303b4385-8b6814758777d498"'], returncode=0, stdout='  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n 25 16158   25  4136    0     0  17719      0 --:--:-- --:--:-- --:--:-- 17675\n100 16158  100 16158    0     0  69171      0 --:--:-- --:--:-- --:--:-- 69051\nSummary:\n   - Profile ID: 88e5c13d303b4385-8b6814758777d498\n   - Task Type: QUERY\n   - Start Time: 2026-09-24 10:32:24\n   - End Time: 2026-09-24 10:32:25\n   - Total: 997ms\n   - Task State: OK\n   - User: root\n   - Default Catalog: internal\n   - Default Db: otel\n   - Sql Statement: SELECT * FROM otel_logs WHERE service_name = \'load-generator\' LIMIT 10\n   - Distributed Plan: N/A\nExecution Summary:\n   - Workload Group: normal\n   - Parse SQL Time: 3ms\n   - Plan Time: 136ms\n     - Garbage Collect During Plan Time: 0ms\n     - Nereids Lock Table Time: 84ms\n     - Nereids Analysis Time: 2ms\n     - Nereids Rewrite Time: 8ms\n       - Nereids Fold Const By BE Time: 0ms\n     - Nereids Collect Table Partition Time: 0ms\n   - Nereids Pre Rewrite By Mv Time: N/A\n     - Nereids Optimize Time: N/A\n     - Nereids Translate Time: 11ms\n       - Init Scan Node Time: N/A\n       - Finalize Scan Node Time: N/A\n         - Get Splits Time: N/A\n         - Get Partitions Time: N/A\n         - Get Partition Files Time: N/A\n         - Sink Set Partition Values Time: N/A\n       - Create Scan Range Time: N/A\n         - Iceberg Scan Metrics: N/A\n         - Paimon Scan Metrics: N/A\n     - Nereids Distribute Time: 14ms\n   - Get Meta Version Time: N/A\n     - Get Partition Version Time: N/A\n     - Get Partition Version Count (hasData): N/A\n     - Get Partition Version Count: N/A\n     - Get Table Version Time: N/A\n     - Get Table Version Count: N/A\n   - Schedule Time: 88ms\n     - Fragment Assign Time: 3ms\n     - Fragment Serialize Time: 41ms\n     - Fragment RPC Phase1 Time: 38ms\n     - Fragment RPC Phase2 Time: 6ms\n     - Fragment Compressed Size: 4.19 KB\n     - Fragment RPC Count: 2\n   - Schedule Time Of BE: {"phase1":{"127.0.0.1: 8060":{"RPC Work Time":"27ms","RPC Latency From FE To BE":"5ms","RPC Work Queue Time":"0ms","RPC Latency From BE To FE":"6ms"}},"phase2":{"127.0.0.1: 8060":{"RPC Work Time":"1ms","RPC Latency From FE To BE":"2ms","RPC Work Queue Time":"0ms","RPC Latency From BE To FE":"3ms"}}}\n   - Wait and Fetch Result Time: 769ms\n   - Fetch Result Time: 714ms\n   - Write Result Time: 0ms\n   - Doris Version: doris-4.0.3-rc03-e9096296b8b\n   - Is Nereids: Yes\n   - Is Cached: No\n   - Total Instances Num: 2\n   - Instances Num Per BE: 127.0.0.1:8060:2\n   - Parallel Fragment Exec Instance Num: 4\n   - Trace ID: \n   - Transaction Commit Time: N/A\n   - System Message: N/A\n   - Executed By Frontend: N/A\n   - Splits Assignment Weight: N/A\n\nChangedSessionVariables:\n[\n  {\n    "VarName": "enable_profile",\n    "CurrentValue": "true",\n    "DefaultValue": "false"\n  }\n]\nMergedProfile:\n     Fragments:\n       Fragment 0:\n         Pipeline 0(instance_num=1):\n            - WaitWorkerTime: avg 75.917us, max 75.917us, min 75.917us\n           RESULT_SINK_OPERATOR(id=2147483647):\n             CommonCounters:\n                - ExecTime: avg 2.505ms, max 2.505ms, min 2.505ms\n                - InputRows: sum 0, avg 0, max 0, min 0\n                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - WaitForDependency[RESULT_SINK_OPERATOR_DEPENDENCY]Time: avg 0ns, max 0ns, min 0ns\n             CustomCounters:\n                - WaitForDependencyTime: avg 0ns, max 0ns, min 0ns\n           EXCHANGE_OPERATOR(id=1):\n              - PlanInfo\n                 - offset: 0\n                 - limit: 10\n             CommonCounters:\n                - BlocksProduced: sum 0, avg 0, max 0, min 0\n                - ExecTime: avg 1.32ms, max 1.32ms, min 1.32ms\n                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - RowsProduced: sum 0, avg 0, max 0, min 0\n             CustomCounters:\n                - WaitForDependencyTime: avg 0ns, max 0ns, min 0ns\n                  - WaitForData0: avg 767.158ms, max 767.158ms, min 767.158ms\n       Fragment 1:\n         Pipeline 0(instance_num=1):\n            - WaitWorkerTime: avg 627.415us, max 627.415us, min 627.415us\n           DATA_STREAM_SINK_OPERATOR(dest_id=1):\n             CommonCounters:\n                - ExecTime: avg 2.872ms, max 2.872ms, min 2.872ms\n                - InputRows: sum 0, avg 0, max 0, min 0\n                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - WaitForDependencyTime: avg 0ns, max 0ns, min 0ns\n                  - WaitForRpcBufferQueue: avg 0ns, max 0ns, min 0ns\n             CustomCounters:\n                - BlocksProduced: sum 1, avg 1, max 1, min 1\n                - OverallThroughput: sum 0.0 /sec, avg 0.0 /sec, max 0.0 /sec, min 0.0 /sec\n           OLAP_SCAN_OPERATOR(nereids_id=123. table_name=otel_logs(otel_logs))(id=0):\n              - PlanInfo\n                 - TABLE: otel.otel_logs(otel_logs), PREAGGREGATION: ON\n                 - PREDICATES: (service_name = \'load-generator\')\n                 - partitions=1/5 (p20260924)\n                 - tablets=10/10, tabletList=1790240551126,1790240551128,1790240551130 ...\n                 - cardinality=10, avgRowSize=5585.4287, numNodes=1\n                 - pushAggOp=NONE\n                 - limit: 10\n             CommonCounters:\n                - BlocksProduced: sum 0, avg 0, max 0, min 0\n                - ExecTime: avg 248.613ms, max 248.613ms, min 248.613ms\n                - MemoryUsage: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - MemoryUsagePeak: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - RowsProduced: sum 0, avg 0, max 0, min 0\n                - WaitForDependency[OLAP_SCAN_OPERATOR_DEPENDENCY]Time: avg 157.662ms, max 157.662ms, min 157.662ms\n             CustomCounters:\n                - RuntimeFilterInfo: sum , avg , max , min \n                - ScanBytes: sum 0.00 , avg 0.00 , max 0.00 , min 0.00 \n                - ScanRows: sum 0, avg 0, max 0, min 0\n\nDetailProfile(88e5c13d303b4385-8b6814758777d498):\n  Fragments:\n    Fragment 0:\n      FragmentLevelProfile:(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):\n      Pipeline 0(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):\n        PipelineTask(index=0):\n           - TaskState: FINALIZED\n           - BlockedByDependency: \n           - WakeUpEarly: 0\n           - WaitWorkerTime: 75.917us\n          RESULT_SINK_OPERATOR(id=2147483647):\n            CommonCounters:\n               - ExecTime: 2.505ms\n               - InputRows: 0\n               - MemoryUsage: 0.00 \n               - MemoryUsagePeak: 0.00 \n               - WaitForDependency[RESULT_SINK_OPERATOR_DEPENDENCY]Time: 0ns\n            CustomCounters:\n               - WaitForDependencyTime: 0ns\n          EXCHANGE_OPERATOR(id=1):\n            CommonCounters:\n               - BlocksProduced: 0\n               - ExecTime: 1.32ms\n               - MemoryUsage: 0.00 \n               - MemoryUsagePeak: 0.00 \n               - RowsProduced: 0\n            CustomCounters:\n               - InstanceID: 88e5c13d303b4385-8b6814758777d4a6\n               - WaitForDependencyTime: 0ns\n                 - WaitForData0: 767.158ms\n    Fragment 1:\n      FragmentLevelProfile:(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):\n      Pipeline 0(host=TNetworkAddress(hostname:127.0.0.1, port:9050)):\n        PipelineTask(index=0):\n           - TaskState: FINALIZED\n           - BlockedByDependency: \n           - WakeUpEarly: 0\n           - WaitWorkerTime: 627.415us\n          DATA_STREAM_SINK_OPERATOR(dest_id=1):\n            CommonCounters:\n               - ExecTime: 2.872ms\n               - InputRows: 0\n               - MemoryUsage: 0.00 \n               - MemoryUsagePeak: 0.00 \n               - WaitForDependencyTime: 0ns\n                 - WaitForRpcBufferQueue: 0ns\n            CustomCounters:\n               - BlocksProduced: 1\n               - OverallThroughput: 0.0 /sec\n          OLAP_SCAN_OPERATOR(nereids_id=123. table_name=otel_logs(otel_logs))(id=0):\n            CommonCounters:\n               - BlocksProduced: 0\n               - ExecTime: 248.613ms\n               - MemoryUsage: 0.00 \n               - MemoryUsagePeak: 0.00 \n               - RowsProduced: 0\n               - WaitForDependency[OLAP_SCAN_OPERATOR_DEPENDENCY]Time: 157.662ms\n            CustomCounters:\n               - TopNFilterSourceNodeIds: \n               - PushDownPredicates: Slot ID: 1: [{ComparisonPredicateBase(Column ID: 1, Data Type: VARCHAR, PredicateType: eq, opposite: false, Runtime Filter ID: -1)}, ] \n               - RemainedDownPredicates: \n               - KeyRanges: ScanKeys:ScanKey=[null(0000-01-01 00:00:00) : 9999-12-31 23:59:59.999999]\n               - TabletIds: [1790240551126, 1790240551128, 1790240551130, 1790240551132, 1790240551134, 1790240551136, 1790240551138, 1790240551140, 1790240551142, 1790240551144]\n               - RuntimeFilterInfo: \n               - ScanBytes: 0.00 \n               - ScanRows: 0\n              Scanner:\n                 - ReadColumns: [timestamp, service_name, service_instance_id, trace_id, span_id, severity_number, severity_text, body, resource_attributes, log_attributes, scope_name\n, scope_version]\n                 - PerScannerRunningTime: [1.541us, 1.166us, 2.916us, 1.166us, 2.708us, 5.209us, 4.333us, 2.334us, 6.125us, 5.292us, ]\n                 - PerScannerRowsRead: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ]\n                 - PerScannerWaitTime: [751.792us, 381.916us, 365.834us, 928.250us, 161.125us, 143.583us, 2.122ms, 235.916us, 392.208us, 175.875us, ]\n                 - PerScannerProjectionTime: [0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, 0.000ns, ]\n                 - EOS: True\n                SegmentIterator:\n                   - FileCache: 0ns\n                     - BytesScannedFromCache: 0.00 \n                     - BytesScannedFromPeer: 0.00 \n                     - BytesScannedFromRemote: 0.00 \n                     - BytesWriteIntoCache: 0.00 \n                     - CacheGetOrSetTimer: 0ns\n                     - GetTimer: 0ns\n                     - InvertedIndexBytesScannedFromCache: 0.00 \n                     - InvertedIndexBytesScannedFromPeer: 0.00 \n                     - InvertedIndexBytesScannedFromRemote: 0.00 \n                     - InvertedIndexIOTimer: 0ns\n                     - InvertedIndexLocalIOUseTimer: 0ns\n                     - InvertedIndexNumLocalIOTotal: 0\n                     - InvertedIndexNumPeerIOTotal: 0\n                     - InvertedIndexNumRemoteIOTotal: 0\n                     - InvertedIndexPeerIOUseTimer: 0ns\n                     - InvertedIndexRemoteIOUseTimer: 0ns\n                     - LocalIOUseTimer: 0ns\n                     - LockWaitTimer: 0ns\n                     - NumLocalIOTotal: 0\n                     - NumPeerIOTotal: 0\n                     - NumRemoteIOTotal: 0\n                     - NumSkipCacheIOTotal: 0\n                     - PeerIOUseTimer: 0ns\n                     - ReadCacheFileDirectlyTimer: 0ns\n                     - RemoteIOUseTimer: 0ns\n                     - SetTimer: 0ns\n                     - WaitOtherDownloaderTimer: 0ns\n                     - WriteCacheIOUseTimer: 0ns\n                IndexFilter:\n  LoadChannels:\n\nAppendix:\n\nPhysicalPlan:\nPhysicalResultSink[143] ( outputExprs=[timestamp#0, service_name#1, service_instance_id#2, trace_id#3, span_id#4, severity_number#5, severity_text#6, body#7, resource_attributes#8, log_attributes#9, scope_name#10, scope_version#11] )\n     +--PhysicalLimit[139]@3 ( limit=10, offset=0, phase=GLOBAL, stats=10 )\n        +--PhysicalDistribute[135]@2 ( stats=10, distributionSpec=DistributionSpecGather )\n           +--PhysicalLimit[131]@2 ( limit=10, offset=0, phase=LOCAL, stats=10 )\n              +--PhysicalFilter[127]@1 ( stats=3,451.5, predicates=(service_name#1 = \'load-generator\') )\n                 +--PhysicalOlapScan[otel_logs partitions(1/5)]@0 ( stats=96,267(6903) actualRows=0, operativeSlots=[service_name#1], virtualColumns=[] )\n     PhysicalOlapScan[otel_logs partitions(1/5)]@0 ( stats=96,267(6903) actualRows=0, operativeSlots=[service_name#1], virtualColumns=[] )\n       timestamp#0 -> ndv=52056.0000, min=20260924164055.000000(2026-09-24 16:40:55.847000), max=20260924182655.000000(2026-09-24 18:26:55.379000), count=96267.0000, numNulls=0.0000, avgSizeByte=8.000000, hotValues=(null)\n       service_name#1 -> ndv=1.0000, min=0.000000(), max=0.000000(\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=(\'\':1.0)\n       service_instance_id#2 -> ndv=1.0000, min=0.000000(), max=0.000000(), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=(\'\':1.0)\n       trace_id#3 -> ndv=1.0000, min=0.000000(), max=0.000000(), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=(\'\':1.0)\n       span_id#4 -> ndv=1.0000, min=0.000000(), max=0.000000(\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01), count=96267.0000, numNulls=0.0000, avgSizeByte=16.000000, hotValues=(\'\':1.0)\n       severity_number#5 -> ndv=3.0000, min=9.000000(9), max=17.000000(17), count=96267.0000, numNulls=0.0000, avgSizeByte=4.000000, hotValues=(9:1.0)\n       severity_text#6 -> ndv=3.0000, min=19512286864605184.000000(ERROR), max=24560144725573632.000000(WARN), count=96267.0000, numNulls=0.0000, avgSizeByte=4.000352, hotValues=(\'INFO\':1.0)\n       body#7 -> ndv=82518.0000, min=23210065350192484.000000(RuntimeLogger 2026-09-24 08:40:55,847 INFO (main|1) [LogUtils.stdout():50] StdoutLogger 2026-09-24 08:40:55,844 Build version: doris-4.0.3-rc03), max=23210065350192484.000000(RuntimeLogger 2026-09-24 10:26:55,379 INFO (tablet scheduler|36) [TabletScheduler.runAfterCatalogReady():366] finished to tablet scheduler. cost: 1 ms), count=96267.0000, numNulls=0.0000, avgSizeByte=291.467595, hotValues=(null)\n       resource_attributes#8 -> unknown(96267.0)\n       log_attributes#9 -> unknown(96267.0)\n       scope_name#10 -> ndv=1.0000, min=0.000000(), max=0.000000(\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0

Search for the keyword `RowsInvertedIndexFiltered`. Information similar to the following is displayed:

```text
RowsInvertedIndexFiltered: 11.702K (11702)
```

This indicates that 11,702 rows were filtered out by the inverted index. The index filtered part of the data and improved query efficiency.